// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://vkhcmipmyqgddjnuthxb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraGNtaXBteXFnZGRqbnV0aHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDgzMzgsImV4cCI6MjA3MTg4NDMzOH0.3XGE2CXacUfaFoM_uKn90frlQS_f4ANUHFc6CDZ6DdE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
